Revert "SteveH: support adding SCM information to POMs produced by maven-publish plugin on modern Gradle"
seeing this error everywhere...
09:41:36 Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
09:41:36 	at com.timgroup.gradlejarmangit.GradleJarManGitPlugin.repoInfo(GradleJarManGitPlugin.groovy:29)

This reverts commit 58d351dee20625f11230ba26bf63c2b8c9c6ff4f.